### PR TITLE
Add build script for Linux systems

### PR DESCRIPTION
**Pull request by akien-mga**
Ideally this build script would be greatly simplified in the future
if the main CMake script would chainload the scripts for wrap and atlas
(and maybe tgui2 if it is added as a git submodule)

I made it similar to the monster-rpg-3 build script, and it seems to work fine.
I'm facing a linking issue with allegro, but I'll open a ticket about it.

### CODE REVIEW

**Comment by akien-mga** [comment]
Actually I've managed to link against the shared libraries for allegro, I had just forgotten some of them previously. My binary seems to segfault though, so I guess I got a couple of things wrong in my build script :)

**Comment by trentg** [comment]
It looks fine. Do you have data.cpa in ${BINDIR}/stuff?

**Comment by akien-mga** [comment]
Ah not that was my mistake, I had data.cpa in the same dir as the binary.

**Comment by akien-mga** [comment]
There is still one issue with my build script though, which is the linking of bass and bassmidi. How do you handle it so that your binary looks for the libraries in ${BINDIR}/stuff?

According to the CMake script, you also seem to link against the bass* libraries based on your dev environment in /home/trent, etc.

**Comment by trentg** [comment]
CMake sets an RPATH so it should look in stuff/. I'll accept a patch that looks for simple 'bass' and 'bassmidi'.

**Comment by akien-mga** [comment]
Ah right I missed the RPATH. Everything is OK then I suppose; if people put the bass* libraries in their system's LD_LIBRARY_PATH, it should work too.

As bass and bassmidi are proprietary anyway, it does make much sense to do too much work towards using system-wide bass libraries; currently any distribution of Crystal Picnic needs to bundle the bass* shared libraries, so people can use the $ORIGIN/stuff RPATH.

**Comment by akien-mga** [comment]
If in the future there is a free alternative to bass* implemented, then yes the RPATH could be made opt-in, and a system to look for data at the system-wide level should be designed; but we're not there yet :)

**Pull request merged**
